name: 'Compile & Test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
  workflow_dispatch:

jobs:
  compileNtest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: compile
      run: g++ -O3 example.cpp -o example
    - name: test
      run: ./example
